// historico_mudancas/22 - Projeto Final/rocket-json-completo_aula_front-angular/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { environment } from '../../../environments/environment'

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  email: string;
  password: string;
  errorMessage: string; // Variável para armazenar mensagens de erro

  constructor(private http: HttpClient, private router: Router) { 
    this.email = "";
    this.password = "";
    this.errorMessage = "";
  }

  ngOnInit(): void {
  }

  login(): void {
    const loginData = { email: this.email, senha: this.password };
    this.http.post(`${environment.apiHost}/login`, loginData).subscribe({
      next: (response:any) => {
        
        const token = response.token;
        const now = new Date();
        const expirationDate = new Date(now.getTime() + 24 * 60 * 60 * 1000); // Definir a expiração para 1 dia
        const sessionData = { token: token, expiration: expirationDate.toISOString() };
        sessionStorage.setItem('sessionData', JSON.stringify(sessionData));

        this.router.navigate(['/recursos']);
      },
      error: (error) => {
        this.errorMessage = 'Login ou senha inválidos';
      }
    });
  }
}

<div class="container mt-5">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title text-center">Login</h2>
            <form (submit)="login()">
              <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" [(ngModel)]="email" name="email" placeholder="Digite seu email">
              </div>
              <div class="mb-3">
                <label for="password" class="form-label">Senha</label>
                <input type="password" class="form-control" id="password" [(ngModel)]="password" name="password" placeholder="Digite sua senha">
              </div>
              
              <div *ngIf="errorMessage" class="alert alert-danger">
                {{ errorMessage }}
              </div>

              <div class="text-center">
                <button type="submit" class="btn btn-primary">Entrar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

// historico_mudancas/22 - Projeto Final/actix-web-json-completo-front-react/src/Pages/Login.js
import '../App.css';
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import  Env from '../Environment/Env';

function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleLogin = async (event) => {
    event.preventDefault();

    const loginData = {
      email: email,
      senha: password,
    };

    try {
      const response = await fetch(`${Env.host}/logar`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(loginData),
      });

      if (response.ok) {
        const { token } = await response.json(); // Desestruturando para obter o token
        // Armazenar o token no sessionStorage com um tempo de expiração
        const now = new Date();
        const item = {
          value: token,
          expiry: now.getTime() + (24 * 60 * 60 * 1000), // 24 horas de validade
        };
        sessionStorage.setItem('authToken', JSON.stringify(item));
        navigate('/clientes');
      } else {
        throw new Error('Login ou senha inválidos');
      }
    } catch (error) {
      setError(error.message);
    }
  };

  return (
    <div className="App">
      <div className="login-container">
        <form className="form-signin" onSubmit={handleLogin}>
          <h1 className="h3 mb-3 font-weight-normal">Dados para entrar no sistema</h1>
          {error && <div className="alert alert-danger" role="alert">{error}</div>}
          <label htmlFor="inputEmail" className="sr-only">Endereço de email</label>
          <input
            type="email"
            id="inputEmail"
            className="form-control"
            placeholder="Endereço de email"
            required
            autoFocus
            value={email}
            onChange={e => setEmail(e.target.value)}
          />
          <label htmlFor="inputPassword" className="sr-only">Senha</label>
          <input
            type="password"
            id="inputPassword"
            className="form-control"
            placeholder="Senha"
            required
            value={password}
            onChange={e => setPassword(e.target.value)}
          />
          <button className="btn btn-lg btn-primary btn-block" type="submit">Logar</button>
        </form>
      </div>
    </div>
  );
}

export default Login;
